name: test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
